//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPWeb_NEW.DBConnect
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HLKJobsEntities : DbContext
    {
        public HLKJobsEntities()
            : base("name=HLKJobsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobExecutionType> JobExecutionTypes { get; set; }
        public virtual DbSet<Resource> Resources { get; set; }
        public virtual DbSet<ResourceConfiguration> ResourceConfigurations { get; set; }
        public virtual DbSet<ResourcePool> ResourcePools { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<Run> Runs { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<TaskResult> TaskResults { get; set; }
        public virtual DbSet<JobAncestry> JobAncestries { get; set; }
    }
}
