//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomacionTestCase.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.Guid Guid { get; set; }
        public int JobExecutionTypeId { get; set; }
        public int SetupDependencyTypeId { get; set; }
        public int RegularDependencyTypeId { get; set; }
        public int CleanupDependencyTypeId { get; set; }
        public string CreatedByAlias { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string LastUpdatedByAlias { get; set; }
        public System.DateTime LastUpdatedTime { get; set; }
        public string OwnerAlias { get; set; }
        public Nullable<int> DSLinkJobId { get; set; }
        public Nullable<System.DateTime> DSLinkLastUpdatedTime { get; set; }
        public Nullable<System.Guid> DSLinkGuid { get; set; }
        public string Description { get; set; }
        public int Total { get; set; }
        public Nullable<int> CommonContextId { get; set; }
        public Nullable<int> FeatureId { get; set; }
        public string AssignedToAlias { get; set; }
        public Nullable<bool> IsFreshInstall { get; set; }
        public Nullable<int> ConfigurationOperationId { get; set; }
        public Nullable<int> ExpectedRuntime { get; set; }
        public string Text1 { get; set; }
        public string Text2 { get; set; }
        public string Text3 { get; set; }
        public string Text4 { get; set; }
        public string Keywords { get; set; }
        public Nullable<int> Int1 { get; set; }
        public Nullable<int> Int2 { get; set; }
        public string Url { get; set; }
        public Nullable<int> Priority { get; set; }
        public string ReviewedBy { get; set; }
        public Nullable<System.DateTime> ReviewedDate { get; set; }
        public string CustomXml { get; set; }
        public int DescriptionFormatId { get; set; }
    }
}
