//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPFrm.DBConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobAncestry
    {
        public int ChildJobId { get; set; }
        public int AncestorJobId { get; set; }
        public int ParentTaskId { get; set; }
        public int Depth { get; set; }
        public string Path { get; set; }
    }
}
