//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPFrm.DBConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.Runs = new HashSet<Run>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> FirstScheduleTime { get; set; }
        public Nullable<System.DateTime> LastScheduleTime { get; set; }
        public string ScheduledByAlias { get; set; }
        public int ScheduleTimeout { get; set; }
        public int ResourcePoolId { get; set; }
        public string Mailto { get; set; }
        public string MailCC { get; set; }
        public Nullable<int> SendMailFor { get; set; }
        public System.DateTime ScheduleStartTime { get; set; }
        public System.DateTime ScheduleEndTime { get; set; }
        public Nullable<int> ScheduleRuntimeMinutes { get; set; }
        public int MaxJobsPerRun { get; set; }
        public Nullable<bool> IsIdleRun { get; set; }
        public Nullable<int> CommonContextId { get; set; }
        public bool IsResourceSelected { get; set; }
        public Nullable<bool> IsSmartSchedulerEnabled { get; set; }
        public int RunTimeout { get; set; }
        public Nullable<int> FailureActionId { get; set; }
    
        public virtual ResourcePool ResourcePool { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Run> Runs { get; set; }
    }
}
