// <auto-generated>
//     This code was generated
//     by wd2cs.exe version 5.2.0.2
//     using UIAF version 5.2.0.0
//
//     Command line : "C:\Users\LocalAdminUser\Desktop\UIAF\wd2cs.exe" "C:\Users\LocalAdminUser\Desktop\MicrosoftOMSWindow.wd" /top_directory "C:\Users\LocalAdminUser\Desktop" /dynamic false /class_prefix SC /extension .cs
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using System;
using System.Drawing;
using System.Text.RegularExpressions;
using UIAF;

namespace UIAF.Hierarchy
{

    /// <summary>
    /// Roles.Pane
    /// </summary>
    [Role(Roles.Pane)]
    public partial class MicrosoftOMSWindow
    {
        private static ACWithChildren s_This_AO;
        private static ACWithChildren This_AO
        {
            get
            {
                if ((s_This_AO == null))
                {
                    s_This_AO = new ACWithChildren();
                    s_This_AO.AccObject = new AccObject(null, Roles.Pane, ";Name => \'{0}\';Name => \'{0}\' && Role = \'window\' && ClassName = \'TabWindowClass\';N" +
                            "ame => \'{1}\' && Role = \'pane\'", new string[] {
                                "Internet Explorer",
                                "Microsoft Operations Management Suite"}, "MicrosoftOMSWindow");
                }
                return s_This_AO;
            }
        }
        public static AccObject AccObject
        {
            get
            {
                return This_AO.AccObject;
            }
            set
            {
                This_AO.AccObject = value;
            }
        }
        public static Rectangle BoundingRectangle
        {
            get
            {
                return This_AO.BoundingRectangle;
            }
        }
        public static Boolean Checked
        {
            get
            {
                return This_AO.Checked;
            }
            set
            {
                This_AO.Checked = value;
            }
        }
        public static Int32 ChildCount
        {
            get
            {
                return This_AO.ChildCount;
            }
        }
        public static AccObject[] Children
        {
            get
            {
                return This_AO.Children;
            }
        }
        public static String CustomRole
        {
            get
            {
                return This_AO.CustomRole;
            }
        }
        public static String Description
        {
            get
            {
                return This_AO.Description;
            }
        }
        public static Boolean Enabled
        {
            get
            {
                return This_AO.Enabled;
            }
        }
        public static Boolean EnableVerifiers
        {
            get
            {
                return This_AO.EnableVerifiers;
            }
            set
            {
                This_AO.EnableVerifiers = value;
            }
        }
        public static Boolean Exists
        {
            get
            {
                return This_AO.Exists;
            }
        }
        public static Boolean Expanded
        {
            get
            {
                return This_AO.Expanded;
            }
            set
            {
                This_AO.Expanded = value;
            }
        }
        public static Boolean Gone
        {
            get
            {
                return This_AO.Gone;
            }
        }
        public static String LastQIDValue
        {
            get
            {
                return This_AO.LastQIDValue;
            }
        }
        [ObsoleteAttribute("Location property is deprecated, please use BoundingRectangle instead")]
        public static Rectangle Location
        {
            get
            {
                return This_AO.BoundingRectangle;
            }
        }
        public static String Name
        {
            get
            {
                return This_AO.Name;
            }
            set
            {
                This_AO.Name = value;
            }
        }
        public static Object Object
        {
            get
            {
                return This_AO.Object;
            }
        }
        public static String Role
        {
            get
            {
                return This_AO.Role;
            }
        }
        public static Boolean Selected
        {
            get
            {
                return This_AO.Selected;
            }
            set
            {
                This_AO.Selected = value;
            }
        }
        public static String State
        {
            get
            {
                return This_AO.State;
            }
        }
        public static String Value
        {
            get
            {
                return This_AO.Value;
            }
            set
            {
                This_AO.Value = value;
            }
        }
        public static Boolean Visible
        {
            get
            {
                return This_AO.Visible;
            }
        }
        public static String WDPath
        {
            get
            {
                return This_AO.WDPath;
            }
        }
        public static void BringUp()
        {
            This_AO.BringUp();
        }
        public static void DoDefaultAction()
        {
            This_AO.DoDefaultAction();
        }
        public static AccObject FindChild(params String[] NameOrQIDOrResKey)
        {
            return This_AO.FindChild(NameOrQIDOrResKey);
        }
        public static AccObject FindChild(Regex RegexName)
        {
            return This_AO.FindChild(RegexName);
        }
        public static AccObject FindChild(Char Separator, String ConcatenetedNamesOrQIDsOrResKeys)
        {
            return This_AO.FindChild(Separator, ConcatenetedNamesOrQIDsOrResKeys);
        }
        public static AccObject FindChild(Regex RegexName, String Role)
        {
            return This_AO.FindChild(RegexName, Role);
        }
        public static AccObject FindChild(String QID, String[] ResKeys)
        {
            return This_AO.FindChild(QID, ResKeys);
        }
        public static AccObject FindChildByValue(Regex RegexValue)
        {
            return This_AO.FindChildByValue(RegexValue);
        }
        public static AccObject FindChildByValue(String Value)
        {
            return This_AO.FindChildByValue(Value);
        }
        public static AccObject FindChildByValue(Regex RegexValue, String Role)
        {
            return This_AO.FindChildByValue(RegexValue, Role);
        }
        public static AccObject FindChildByValue(String Value, Boolean Exact)
        {
            return This_AO.FindChildByValue(Value, Exact);
        }
        public static AccObject FindChildByValue(String Value, String Role)
        {
            return This_AO.FindChildByValue(Value, Role);
        }
        public static AccObject FindChildByValue(String Value, Boolean Exact, String Role)
        {
            return This_AO.FindChildByValue(Value, Exact, Role);
        }
        public static AccObject[] FindChildren(String QID)
        {
            return This_AO.FindChildren(QID);
        }
        public static AccObject[] FindChildren(String QID, String[] ResKeys)
        {
            return This_AO.FindChildren(QID, ResKeys);
        }
        public static void Type(String Keys, Boolean Literal = false, Boolean Unicode = false)
        {
            This_AO.Type(Keys, Literal, Unicode);
        }
        public static void WaitForGone()
        {
            This_AO.WaitForGone();
        }
        public static void WaitForGone(Int32 Timeout)
        {
            This_AO.WaitForGone(Timeout);
        }
        public static void WaitForGone(Int32 Timeout, Int32 PollInterval)
        {
            This_AO.WaitForGone(Timeout, PollInterval);
        }
        public static AccObject WaitForInit()
        {
            return This_AO.WaitForInit();
        }
        public static AccObject WaitForInit(Int32 Timeout)
        {
            return This_AO.WaitForInit(Timeout);
        }
        public static AccObject WaitForName(params String[] AnyValue)
        {
            return This_AO.WaitForName(AnyValue);
        }
        public static AccObject WaitForName(String[] AnyValue, Int32 Timeout)
        {
            return This_AO.WaitForName(AnyValue, Timeout);
        }
        public static AccObject WaitForName(String ExpectedValue, Int32 Timeout)
        {
            return This_AO.WaitForName(ExpectedValue, Timeout);
        }
        public static AccObject WaitForName(StringOperator Operator, params String[] AnyValue)
        {
            return This_AO.WaitForName(Operator, AnyValue);
        }
        public static AccObject WaitForName(String[] AnyValue, Int32 Timeout, Int32 PollInterval)
        {
            return This_AO.WaitForName(AnyValue, Timeout, PollInterval);
        }
        public static AccObject WaitForName(String ExpectedValue, Int32 Timeout, Int32 PollInterval)
        {
            return This_AO.WaitForName(ExpectedValue, Timeout, PollInterval);
        }
        public static AccObject WaitForName(StringOperator Operator, String ExpectedValue, Int32 Timeout)
        {
            return This_AO.WaitForName(Operator, ExpectedValue, Timeout);
        }
        public static AccObject WaitForName(StringOperator Operator, String[] AnyValue, Int32 Timeout)
        {
            return This_AO.WaitForName(Operator, AnyValue, Timeout);
        }
        public static AccObject WaitForName(StringOperator Operator, String[] AnyValue, Int32 Timeout, Int32 PollInterval)
        {
            return This_AO.WaitForName(Operator, AnyValue, Timeout, PollInterval);
        }
        public static AccObject WaitForName(StringOperator Operator, String ExpectedValue, Int32 Timeout, Int32 PollInterval)
        {
            return This_AO.WaitForName(Operator, ExpectedValue, Timeout, PollInterval);
        }
        public static void WaitForNotShown()
        {
            This_AO.WaitForNotShown();
        }
        public static void WaitForNotShown(Boolean WaitForReady)
        {
            This_AO.WaitForNotShown(WaitForReady);
        }
        public static void WaitForNotShown(Int32 Timeout)
        {
            This_AO.WaitForNotShown(Timeout);
        }
        public static void WaitForNotShown(Int32 Timeout, Boolean WaitForReady)
        {
            This_AO.WaitForNotShown(Timeout, WaitForReady);
        }
        public static void WaitForNotShown(Int32 WaitForReadyTimeout, Int32 WaitForGoneTimeout)
        {
            This_AO.WaitForNotShown(WaitForReadyTimeout, WaitForGoneTimeout);
        }
        public static void WaitForNotShown(Int32 Timeout, Boolean WaitForReady, Int32 PollInterval)
        {
            This_AO.WaitForNotShown(Timeout, WaitForReady, PollInterval);
        }
        public static void WaitForNotShown(Int32 WaitForReadyTimeout, Int32 WaitForGoneTimeout, Int32 PollInterval)
        {
            This_AO.WaitForNotShown(WaitForReadyTimeout, WaitForGoneTimeout, PollInterval);
        }
        public static AccObject WaitForReady()
        {
            return This_AO.WaitForReady();
        }
        public static AccObject WaitForReady(Int32 Timeout)
        {
            return This_AO.WaitForReady(Timeout);
        }
        public static AccObject WaitForState(String StateValue, Boolean Contained)
        {
            return This_AO.WaitForState(StateValue, Contained);
        }
        public static AccObject WaitForState(String StateValue, Boolean Contained, Int32 Timeout)
        {
            return This_AO.WaitForState(StateValue, Contained, Timeout);
        }
        public static AccObject WaitForState(String StateValue, Boolean Contained, Int32 Timeout, Int32 PollInterval)
        {
            return This_AO.WaitForState(StateValue, Contained, Timeout, PollInterval);
        }
        public static AccObject WaitForValue(params String[] AnyValue)
        {
            return This_AO.WaitForValue(AnyValue);
        }
        public static AccObject WaitForValue(String[] AnyValue, Int32 Timeout)
        {
            return This_AO.WaitForValue(AnyValue, Timeout);
        }
        public static AccObject WaitForValue(String ExpectedValue, Int32 Timeout)
        {
            return This_AO.WaitForValue(ExpectedValue, Timeout);
        }
        public static AccObject WaitForValue(StringOperator Operator, params String[] AnyValue)
        {
            return This_AO.WaitForValue(Operator, AnyValue);
        }
        public static AccObject WaitForValue(String[] AnyValue, Int32 Timeout, Int32 PollInterval)
        {
            return This_AO.WaitForValue(AnyValue, Timeout, PollInterval);
        }
        public static AccObject WaitForValue(String ExpectedValue, Int32 Timeout, Int32 PollInterval)
        {
            return This_AO.WaitForValue(ExpectedValue, Timeout, PollInterval);
        }
        public static AccObject WaitForValue(StringOperator Operator, String ExpectedValue, Int32 Timeout)
        {
            return This_AO.WaitForValue(Operator, ExpectedValue, Timeout);
        }
        public static AccObject WaitForValue(StringOperator Operator, String[] AnyValue, Int32 Timeout)
        {
            return This_AO.WaitForValue(Operator, AnyValue, Timeout);
        }
        public static AccObject WaitForValue(StringOperator Operator, String[] AnyValue, Int32 Timeout, Int32 PollInterval)
        {
            return This_AO.WaitForValue(Operator, AnyValue, Timeout, PollInterval);
        }
        public static AccObject WaitForValue(StringOperator Operator, String ExpectedValue, Int32 Timeout, Int32 PollInterval)
        {
            return This_AO.WaitForValue(Operator, ExpectedValue, Timeout, PollInterval);
        }
        public static AccObject WaitForVisible()
        {
            return This_AO.WaitForVisible();
        }
        public static AccObject WaitForVisible(Int32 Timeout)
        {
            return This_AO.WaitForVisible(Timeout);
        }
        public static AccObject WaitForVisible(Int32 Timeout, Int32 PollInterval)
        {
            return This_AO.WaitForVisible(Timeout, PollInterval);
        }
    }
}
